name: vira
version: git
summary: VIRA
description: A Calculator for Calculating
base: core18
confinement: devmode

parts:
  vira:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six

apps:
  vira:
    command: vira