name: vira
version: '1.0.2'
summary: VIRA
description: A Calculator for Calculating
base: core18
confinement: strict

parts:
  vira:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six

apps:
  vira:
    command: vira